server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: false
logging:
  level:
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace
